### ISSUE TITLE
please use more descriptive keys

### ISSUE THREAD

**Issue by schriftgestalt** [mekkablue/Inverter#3]
https://github.com/mekkablue/Inverter/blob/6826f3af8f823c4be2776b6adee006425dff7431/Inverter.glyphsFilter/Contents/Resources/FilterCode.py#L260

add a prefix like `mekkablue.inverter.` or store it in a dict that is set with `mekkablue.inverter`.

**Comment by mekkablue** [comment]
Yes. The plug-in is up for a rewrite anyway. Will use the opportunity.
